### ISSUE TITLE
Dependency deepriemanniannet in crossval_utils.py 

### ISSUE THREAD

**Issue by chirathyh** [Roche/neuro-green#1]
Would you be able to provide some guidance regarding the dependency "deepriemanniannet", how to install this module.
Thanks and have a nice day.

**Comment by jpaillard** [comment]
Hi @chirathyh, 
Thank you for the feedback. 
I solved the broken dependency. Let me know if it works on your side.

**Comment by chirathyh** [comment]
Dear @jpaillard, thank you very much. Yes it works. Have a nice day.
